export const productSelectProperty = {
  productsIdSelect: ["product.id", "product.name", "product.type"],
  productsSelect: [
    "product.name",
    "product.price",
    "product.type",
    "Image.url",
    "StarRate.averageScore",
    "Review",
    "Inquiry",
  ],
  productSelect: [
    "product.id",
    "product.name",
    "product.price",
    "product.origin",
    "product.type",
    "product.description",
    "product.quantity",
    "Image.url",
    "StarRate.averageScore",
    "Review",
    "ReviewImage.url",
    "ReviewVideo.url",
    "Inquiry",
    "InquiryImage.url",
    "InquiryVideo.url",
  ],
  productSelectWhenNeedStarRate: ["product", "StarRate.id"],
};
