export const productSelectProperty = {
  productsSelect: [
    "product.name",
    "product.price",
    "product.type",
    "Image.url",
    "StarRate.averageScore",
    "Review",
    "Inquiry",
    "User.id",
  ],
  productSelect: [
    "product.id",
    "product.name",
    "product.price",
    "product.origin",
    "product.type",
    "product.description",
    "product.quantity",
    "Image.url",
    "StarRate.averageScore",
    "product.createdAt",
    "product.updatedAt",
    "Review",
    "Inquiry",
    "ReviewImage.url",
    "ReviewVideo.url",
  ],
  productSelectWithStarRate: [
    "product.id",
    "product.name",
    "product.price",
    "product.origin",
    "product.type",
    "product.description",
    "Image.url",
    "StarRate.id",
    "StarRate.averageScore",
    "product.createdAt",
    "product.updatedAt",
  ],
};
