export const userSelectProperty = {
  userSelect: ["user", "Profile", "Auth", "Activity"],
  userSelectWithActivityProperty: [
    "user",
    "Profile",
    "Auth",
    "Activity",
    "Review",
    "Inquiry",
  ],
  userProfileSelect: [
    "user",
    "Auth.nickname",
    "Auth.email",
    "Auth.userType",
    "Activity.bonusPoint",
    "Activity.purchaseCount",
    "Activity.productInquiryCount",
    "Activity.productReviewCount",
    "Review",
    "Inquiry",
  ],
  userSimpleSelect: [
    "user",
    "user.id",
    "Auth.nickname",
    "Auth.email",
    "Auth.userType",
  ],
};
