export const userSelectProperty = {
  clientUserSelect: ["client", "Profile", "Auth"],
  clientUserProfileSelect: [
    "client",
    "Profile.realname",
    "Profile.birth",
    "Profile.gender",
    "Profile.phonenumber",
    "Auth.nickname",
    "Auth.email",
    "Auth.userType",
    "Review",
    "Inquiry",
    "ReviewImage.url",
    "ReviewVideo.url",
    "InquiryImage.url",
    "InquiryVideo.url",
  ],
  clientUserSimpleSelect: [
    "client",
    "client.id",
    "Auth.nickname",
    "Auth.email",
    "Auth.userType",
  ],
  whenAdminSelectUser: [
    "client",
    "Auth.nickname",
    "Auth.email",
    "Auth.userType",
    "Activity.bonusPoint",
    "Activity.purchaseCount",
    "Activity.productInquiryCount",
    "Activity.productReviewCount",
    "Review",
    "Inquiry",
  ],
};
